version: "3"
services:
  mongo:
    image: mongo
  server:
    build: .
    privileged: true
    ports: 
      - "3000:80"
      - "3001:443"
    environment:
      - DOMAIN_MONGO=mongo
      - USE_HTTPS=true
    volumes:
      - "./cert:/app/cert"
    restart: always
    depends_on: 
      - mongo
